version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: yarn test
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
  deploy:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Store Google Cloud Keyfile
          command: echo $GCLOUD_SERVICE_KEY > gcloud-service-key.json
      - run:
          name: Commit Keyfile
          command: |
            git config user.name  circle-ienavi-conversion-store
            git config user.email circle-ienavi-conversion-store@colorfulcomapny.co.jp
            git add gcloud-service-key.json
            git commit -m 'add gcloud service key'
      - run: 
          name: Setup Auth
          command: gcloud auth activate-service-account --key-file=gcloud-service-key.json
      - run: 
          name: Setup Project
          command: gcloud --quiet config set project "$GOOGLE_CLOUD_PROJECT_ID"
      - run: 
          name: Funcitons Dployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              gcloud functions deploy "$GOOGLE_CLOUD_FUNCTION_NAME"                --region=asia-northeast1 --trigger-resource="$GOOGLE_CLOUD_STORAGE_NAME"         --trigger-event=google.storage.object.finalize --stage-bucket="$GOOGLE_CLOUD_STAGE_BUCKET"                --entry-point=storedConversion
              gcloud functions deploy "$GOOGLE_CLOUD_PUBSUB_FUNCTION_NAME"         --region=asia-northeast1                                                         --trigger-topic=missingConversion              --stage-bucket="$GOOGLE_CLOUD_STAGE_PUBSUB_BUCKET"         --entry-point=missingConversions
            else
              gcloud functions deploy "$GOOGLE_CLOUD_FUNCTION_NAME-staging"        --region=asia-northeast1 --trigger-resource="$GOOGLE_CLOUD_STORAGE_NAME-staging" --trigger-event=google.storage.object.finalize --stage-bucket="$GOOGLE_CLOUD_STAGE_BUCKET-staging"        --entry-point=storedConversion
              gcloud functions deploy "$GOOGLE_CLOUD_PUBSUB_FUNCTION_NAME-staging" --region=asia-northeast1                                                         --trigger-topic=missingConversionStaging	     --stage-bucket="$GOOGLE_CLOUD_STAGE_PUBSUB_BUCKET-staging" --entry-point=missingConversions
            fi
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - /pull-req\/.*/
                - /release\/.*/
                - /hotfix\/.*/
      - deploy:
          requires:
            - build
